/*
--1.CREAR LA TABLA TEMPORAL #AUTOS(CLAVE, MARCA, MODELO, STOCK, PRECIO).
--2.CREAR UN SP QUE RECIBA LOS 5 PARAMETROS Y HAGA LA INSERCION EN LA #AUTOS.
--3.CREAR UN SP QUE RECIBA 2 PARAMETROS(MARCA, PORCENTAJE), ACTUALIZAR EL PRECIO DE TODOS LOS AUTOMOVILES DE LA MARCA
--  SOLICITADA, DESCONTANDO EL PORCENATAJE ENVIADO.
--4.CREAR UN SP QUE RECIBA 3 PARAMETROS(MARCA, MODELO, CANTIDAD), ACTUALIZAR EL STOCK DEL AUTOMOVIL VENDIDO, REDUECIENDO 
--  LA CANTIDAD DE PIEZAS VENDIDAD.

--NOTA: TODOS LOS SP DEBEN VALIDAR QUE LA INFORMACIÓN EXISTA, DE LO CONTRARIO MANDAR UN MENSAJE INDICANDO ESE DETALLE.
*/
DELETE  #AUTO
CREATE TABLE #AUTO(
	CLAVE INT PRIMARY KEY NOT NULL,
	MARCA VARCHAR(30) NOT NULL,
	MODELO VARCHAR(15) NOT NULL,
	STOCK INT NOT NULL,
	PRECIO FLOAT NOT NULL
);

--2.CREAR UN SP QUE RECIBA LOS 5 PARAMETROS Y HAGA LA INSERCION EN LA #AUTOS.
--a)Verificar que la clave del vehiculo no exista 
--b)Si la clave no existe entonces insertamos los datos en la tabla temporal
--c)En dado caso de que la clave exista mandar un mensaje de error.

CREATE OR ALTER PROCEDURE SP_INSERCION_AUTOS (@CLAVE INT,@MARCA VARCHAR(30),@MODELO VARCHAR(15),@STOCK INT,@PRECIO FLOAT)
AS
BEGIN 
	DECLARE @ClaveRepetida VARCHAR(40) = 'La clave: '+ CONVERT(NVARCHAR(10),@CLAVE) + ' del vehiculo es incorrecta'
	DECLARE @StockPrecioIncorrecto VARCHAR(60) = 'El stock: '+CONVERT(nvarchar(10),@STOCK)+ ' o el precio: $'+CONVERT(nvarchar(20),@PRECIO)+ ' es incorrecto' 

	IF NOT EXISTS (SELECT * FROM #AUTO WHERE CLAVE = @CLAVE)
		BEGIN 
			IF @STOCK >= 0 AND @PRECIO >= 100000
				BEGIN  
					 INSERT INTO #AUTO
					 VALUES(@CLAVE,@MARCA,@MODELO,@STOCK,@PRECIO)
				END
			ELSE
				BEGIN
					RAISERROR(@StockPrecioIncorrecto,16,1);	
				END
		END
	ELSE 
		BEGIN
			RAISERROR(@ClaveRepetida,16,1);
		END
END;

EXEC SP_INSERCION_AUTOS 1,'CHEVROLET','TORMENTA',10,400000
EXEC SP_INSERCION_AUTOS 2,'CHEVROLET','LLUVIA',40,800000
EXEC SP_INSERCION_AUTOS 3,'CHEVROLET','TRUENO',60,190000
EXEC SP_INSERCION_AUTOS 4,'CHEVROLET','HURACAN',250,300000
EXEC SP_INSERCION_AUTOS 5,'CHEVROLET','VERANO',109,200000

EXEC SP_INSERCION_AUTOS 6,'CHEVROLET','TORMENTA',10,560000
EXEC SP_INSERCION_AUTOS 7,'CHEVROLET','TORMENTA',80,650000
EXEC SP_INSERCION_AUTOS 8,'CHEVROLET','TORMENTA',30,770000
EXEC SP_INSERCION_AUTOS 9,'CHEVROLET','TORMENTA',20,840000
EXEC SP_INSERCION_AUTOS 1,'CHEVROLET','TORMENTA',90,320000

SELECT * FROM #AUTO


--3.CREAR UN SP QUE RECIBA 2 PARAMETROS(MARCA, PORCENTAJE), ACTUALIZAR EL PRECIO DE TODOS LOS AUTOMOVILES DE LA MARCA
--SOLICITADA, DESCONTANDO EL PORCENATAJE ENVIADO.
CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_PRECIO(@MARCA VARCHAR(20),@PORCENTAJE FLOAT)
AS 
BEGIN
	DECLARE @MarcaIncorrecta VARCHAR(50) = 'La marca del vehiculo: '+CONVERT(NVARCHAR(30),@MARCA)+ ' o el porcentaje: '+CONVERT(NVARCHAR(30),@PORCENTAJE)+' es incorrecto'
	IF EXISTS (SELECT * FROM #AUTO WHERE MARCA = @MARCA)
		BEGIN 
			IF @PORCENTAJE > 0 AND @PORCENTAJE < 100
				BEGIN 
					UPDATE #AUTO 
					SET Precio = Precio - (Precio*(@PORCENTAJE/100))
					WHERE Marca = @MARCA
				END
		END
	ELSE 
		BEGIN
			RAISERROR(@MarcaIncorrecta,16,1);
		END
END;

SELECT * FROM #AUTO;
EXEC SP_ACTUALIZAR_PRECIO 'CHEVROLET',20


SELECT * FROM #AUTO WHERE MARCA = 'CHEVROLET';

SELECT Marca,Stock,Precio, (Precio-(Precio*0.20)) AS 'Descuento'
FROM  #AUTO


--4.CREAR UN SP QUE RECIBA 3 PARAMETROS(MARCA, MODELO, CANTIDAD), ACTUALIZAR EL STOCK DEL AUTOMOVIL VENDIDO, REDUCIENDO 
--  LA CANTIDAD DE PIEZAS VENDIDAD.

--A) Verificar que exista la Marca y el Modelo 
--B) Actualizar la cantidad introducida por el usuario restando el numero ingresado 
--C) Si no existe la marca y el modelo mandar un mensaje de error

CREATE OR ALTER PROCEDURE SP_ACTUALIAR_STOCK(@MARCA VARCHAR(15),@MODELO VARCHAR(15),@CANTIDAD INT)
AS
BEGIN
	DECLARE @ErorMarcaModelo VARCHAR(40) = 'No existe la marca: '+@MARCA+ ' y no existe el modelo: ' +@MODELO;

	IF EXISTS (SELECT * FROM #AUTO WHERE MARCA = @MARCA AND MODELO = @MODELO)
	BEGIN 
		IF @CANTIDAD >0 
			BEGIN
				UPDATE #AUTO 
				SET STOCK = STOCK -@CANTIDAD
				WHERE MARCA = @MARCA AND MODELO = @MODELO
			END
		ELSE 
			BEGIN 
				RAISERROR(@ErorMarcaModelo,16,1);
			END
	END 
END;

EXEC SP_ACTUALIAR_STOCK 'CHEVROLET','LLUVIA',3
--
SELECT * FROM #AUTO 
